#!/usr/bin/env bash
#Displays hours from 0 to 12
#Displays minutes from 1 to 59


hour=0
minute=1
while [ $hour -le 12 ]
do
	echo Hour: $hour
	while [ $minute -le 59 ]
	do
		echo $minute
		(( minute++ ))
	done
	(( hour++ ))
	minute=0
done
