#!/usr/bin/env bash
#Provides imformation on school file


inputfile="school"
if [ -e $inputfile ]
then
	echo "school file exists"
	if [ -s $inputfile ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $inputfile ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
